// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto
#ifndef GRPC_masterworker_2eproto__INCLUDED
#define GRPC_masterworker_2eproto__INCLUDED

#include "masterworker.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace masterworker {

class MapReduceMaster final {
 public:
  static constexpr char const* service_full_name() {
    return "masterworker.MapReduceMaster";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status MapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::masterworker::MapReduceReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReduceReply>> AsyncMapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReduceReply>>(AsyncMapReduceTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReduceReply>> PrepareAsyncMapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReduceReply>>(PrepareAsyncMapReduceTaskRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void MapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MapReduceTask(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::masterworker::MapReduceReply* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReduceReply>* AsyncMapReduceTaskRaw(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::MapReduceReply>* PrepareAsyncMapReduceTaskRaw(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status MapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::masterworker::MapReduceReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>> AsyncMapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>>(AsyncMapReduceTaskRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>> PrepareAsyncMapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>>(PrepareAsyncMapReduceTaskRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void MapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response, std::function<void(::grpc::Status)>) override;
      void MapReduceTask(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::masterworker::MapReduceReply* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>* AsyncMapReduceTaskRaw(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>* PrepareAsyncMapReduceTaskRaw(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MapReduceTask_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_MapReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_MapReduceTask() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MapReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapReduceTask(::grpc::ServerContext* context, ::masterworker::MapReduceQuery* request, ::grpc::ServerAsyncResponseWriter< ::masterworker::MapReduceReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MapReduceTask<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_MapReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_MapReduceTask() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::masterworker::MapReduceQuery, ::masterworker::MapReduceReply>(
          [this](::grpc::ServerContext* context,
                 const ::masterworker::MapReduceQuery* request,
                 ::masterworker::MapReduceReply* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->MapReduceTask(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_MapReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_MapReduceTask<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MapReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_MapReduceTask() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MapReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MapReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_MapReduceTask() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MapReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMapReduceTask(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_MapReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_MapReduceTask() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->MapReduceTask(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_MapReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void MapReduceTask(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MapReduceTask : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_MapReduceTask() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::masterworker::MapReduceQuery, ::masterworker::MapReduceReply>(std::bind(&WithStreamedUnaryMethod_MapReduceTask<BaseClass>::StreamedMapReduceTask, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_MapReduceTask() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMapReduceTask(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterworker::MapReduceQuery,::masterworker::MapReduceReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_MapReduceTask<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_MapReduceTask<Service > StreamedService;
};

}  // namespace masterworker


#endif  // GRPC_masterworker_2eproto__INCLUDED
