// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto

#include "masterworker.pb.h"
#include "masterworker.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace masterworker {

static const char* MapReduceMaster_method_names[] = {
  "/masterworker.MapReduceMaster/MapReduceTask",
};

std::unique_ptr< MapReduceMaster::Stub> MapReduceMaster::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MapReduceMaster::Stub> stub(new MapReduceMaster::Stub(channel));
  return stub;
}

MapReduceMaster::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_MapReduceTask_(MapReduceMaster_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MapReduceMaster::Stub::MapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::masterworker::MapReduceReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_MapReduceTask_, context, request, response);
}

void MapReduceMaster::Stub::experimental_async::MapReduceTask(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MapReduceTask_, context, request, response, std::move(f));
}

void MapReduceMaster::Stub::experimental_async::MapReduceTask(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::masterworker::MapReduceReply* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_MapReduceTask_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>* MapReduceMaster::Stub::AsyncMapReduceTaskRaw(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::masterworker::MapReduceReply>::Create(channel_.get(), cq, rpcmethod_MapReduceTask_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::masterworker::MapReduceReply>* MapReduceMaster::Stub::PrepareAsyncMapReduceTaskRaw(::grpc::ClientContext* context, const ::masterworker::MapReduceQuery& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::masterworker::MapReduceReply>::Create(channel_.get(), cq, rpcmethod_MapReduceTask_, context, request, false);
}

MapReduceMaster::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MapReduceMaster_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MapReduceMaster::Service, ::masterworker::MapReduceQuery, ::masterworker::MapReduceReply>(
          std::mem_fn(&MapReduceMaster::Service::MapReduceTask), this)));
}

MapReduceMaster::Service::~Service() {
}

::grpc::Status MapReduceMaster::Service::MapReduceTask(::grpc::ServerContext* context, const ::masterworker::MapReduceQuery* request, ::masterworker::MapReduceReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace masterworker

